export const SET_SHOW_NAV = 'SET_SHOW_NAV';

export const SET_LOAD = 'SET_LOAD';

export const SET_SEARCH = 'SET_SEARCH';

export const SET_CURRENT_LAN = 'SET_CURRENT_LAN';

export const SET_DETAIL_VALUE = 'SET_DETAIL_VALUE';

export const SET_LAN_LIST = 'SET_LAN_LIST';

export const SET_TRENDING_LIST = 'SET_TRENDING_LIST';

export const SET_SEARCH_TRENDING_LIST = 'SET_SEARCH_TRENDING_LIST';

export const SET_STARS_LIST = 'SET_STARS_LIST';

export const SET_HOTWORDS = 'SET_HOTWORDS';

export const SET_SEARCH_LOADMORE_INDEX = 'SET_SEARCH_LOADMORE_INDEX';

export const SET_STARS_LOADMORE_INDEX = 'SET_STARS_LOADMORE_INDEX';

export const SET_CACHE_KEYWORDS = 'SET_CACHE_KEYWORDS';

export const SET_STARS_CACHE_KEYWORDS = 'SET_STARS_CACHE_KEYWORDS';

export const SET_TRENDING_SCROLL_POSITION = 'SET_TRENDING_SCROLL_POSITION';

export const SET_SEARCH_SCROLL_POSITION = 'SET_SEARCH_SCROLL_POSITION';

export const SET_STARS_SCROLL_POSITION = 'SET_STARS_SCROLL_POSITION';
